apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: musicians-service-claim0
  name: musicians-service-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
