steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/musicians-service', '-f', 'musicians/Dockerfile', '.']
    dir: musicians
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/musicians-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/users-service', '-f', 'users/Dockerfile', '.']
    dir: users
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/users-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/frontend-service', '-f', 'frontend/Dockerfile', '.']
    dir: frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/frontend-service']
images:
  - 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/musicians-service'
  - 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/users-service'
  - 'europe-west3-docker.pkg.dev/musicians-app-429616/musicians-repo/frontend-service'
