version: "3.8"
services:
  users-service:
    build: ./users
    container_name: users-container
    environment:
      DEBUG: "${DEBUG}"
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      LOG_LEVEL: "${LOG_LEVEL}"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"