version: "3.8"
services:
  users-service:
    build: ./users
    container_name: users-container
    environment:
      DEBUG: "${DEBUG}"
      SECRET_KEY: "${SECRET_KEY}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    volumes:
      - ./users/src:/project_dir
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8020:8000"