apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: users-service
    spec:
      containers:
      - args:
        - python
        - manage.py
        - runserver
        - 0.0.0.0:8000
        env:
        - name: DB_HOST
        - name: DB_NAME_USERS
        - name: DB_PASSWORD
        - name: DB_PORT
        - name: DB_USER
        - name: DEBUG
        - name: JWT_PRIVATE_KEY
        - name: JWT_PUBLIC_KEY
        - name: LOG_LEVEL
        - name: SECRET_KEY
        image: users-service
        imagePullPolicy: ""
        name: users-container
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
