# Generated by Django 4.1 on 2023-12-14 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicians',
            options={'ordering': ['-time_update'], 'verbose_name': 'Famous musicians', 'verbose_name_plural': 'Famous musicians'},
        ),
        migrations.AlterModelOptions(
            name='styles',
            options={'ordering': ['pk'], 'verbose_name': 'Music style', 'verbose_name_plural': 'Music styles'},
        ),
        migrations.AddField(
            model_name='musicians',
            name='author',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicians',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publishing'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.styles', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Link for video'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Style'),
        ),
    ]
