# Generated by Django 4.1 on 2023-12-16 21:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_alter_musicians_options_alter_styles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='styles',
            options={'verbose_name': 'Music style', 'verbose_name_plural': 'Music styles'},
        ),
        migrations.AlterField(
            model_name='musicians',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
