# Generated by Django 4.1 on 2023-12-17 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_alter_styles_options_alter_musicians_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^([A-Z][\\w]*\\s?){3,30}$')], verbose_name='Title'),
        ),
    ]
