# Generated by Django 4.1 on 2023-12-19 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_alter_musicians_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid title with 3 to 30 characters.Each word should start with an uppercase letter, and only letters and single spaces are allowed between words.', regex='^[A-Z][A-Za-z]*(?:\\s[A-Z][A-Za-z]*){0,29}$')], verbose_name='Title'),
        ),
    ]
