# Generated by Django 4.1 on 2023-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_alter_musicians_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='Content'),
        ),
    ]
