# Generated by Django 4.1 on 2023-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_alter_musicians_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='content',
            field=models.TextField(max_length=8000, verbose_name='Content'),
        ),
    ]
