apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    service: kong
spec:
  selector:
    service: kong
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
