apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-stats-consumer
  name: user-stats-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-stats-consumer
  template:
    metadata:
      labels:
        network/app-network: "true"
        service: user-stats-consumer
    spec:
      containers:
      - args:
        - python
        - manage.py
        - consume_user_stats
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: USER_STATS_CONSUMER_DEBUG

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: USER_STATS_CONSUMER_LOG_LEVEL

        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_HOST

        - name: DB_NAME_USERS
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_NAME_USERS

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_PASSWORD

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_PORT

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_USER

        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: JWT_PRIVATE_KEY

        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: JWT_PUBLIC_KEY

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: SECRET_KEY

        image: feelwork/musicians-users-service:1.0.5
        name: user-stats-consumer
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

      restartPolicy: Always
