apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: musicians-service
  name: musicians-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: musicians-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: musicians-service
    spec:
      containers:
      - args:
        - gunicorn
        - --workers
        - "2"
        - --threads
        - "4"
        - --bind
        - 0.0.0.0:8000
        - mus_proj.wsgi:application
#        - python
#        - manage.py
#        - runserver
#        - 0.0.0.0:8000
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: MUSICIANS_DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: MUSICIANS_LOG_LEVEL
        - name: GCP_STORAGE_IS_USED
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: GCP_STORAGE_IS_USED
        - name: GS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: GS_BUCKET_NAME
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: GOOGLE_APPLICATION_CREDENTIALS
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_HOST
        - name: DB_NAME_MUSICIANS
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_NAME_MUSICIANS
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: DB_USER
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: musicians-secret
              key: SECRET_KEY
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: musicians-config
              key: REDIS_URL
        image: feelwork/musicians-musicians-service:1.0.0
        name: musicians-container
      restartPolicy: Always