# Generated by Django 5.0.6 on 2024-06-08 16:59

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid title with 3 to 30 characters.Each word should start with an uppercase letter, and only letters and single spaces between words are allowed .', regex='^[A-Z][A-Za-z]*(?:\\s[A-Z][A-Za-z]*){0,29}$')], verbose_name='Style')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid title with 3 to 30 characters.Each word should start with an uppercase letter, and only letters and single spaces between words are allowed .', regex='^[A-Z][A-Za-z]*(?:\\s[A-Z][A-Za-z]*){0,29}$')], verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', models.TextField(max_length=8000, validators=[django.core.validators.MinLengthValidator(80)], verbose_name='Content')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publishing')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Link for video')),
                ('author_id', models.PositiveIntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.style', verbose_name='Style')),
            ],
            options={
                'ordering': ['-time_update'],
            },
        ),
    ]
