# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    env:
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_NAME_USERS: ${{ secrets.DB_NAME_USERS }}
      DB_NAME_MUSICIANS: ${{ secrets.DB_NAME_MUSICIANS }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      shell: bash

    - name: Give execute permissions to Docker Compose binary
      run: sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run services
      run: docker-compose up --build -d

    - name: Wait for services to be ready
      run: |
        # Wait for users service
        for i in {1..2}; do
          if curl -s http://localhost:8020/; then
            echo "Users service is ready."
            break
          fi
          echo "Waiting for users service to be ready..."
          sleep 5
        done

        # Wait for musicians service
        for i in {1..2}; do
          if curl -s http://localhost:8000/; then
            echo "Musicians service is ready."
            break
          fi
          echo "Waiting for musicians service to be ready..."
          sleep 5
        done

    - name: Check users service status
      run: |
        curl -s http://localhost:8020/ || echo "Users service is not responding."

    - name: Check musicians service status
      run: |
        curl -s http://localhost:8000/ || echo "Musicians service is not responding."

    - name: Check users service logs
      run: docker logs users-container || echo "Failed to fetch users service logs."

    - name: Check musicians service logs
      run: docker logs musicians-container || echo "Failed to fetch musicians service logs."

    - name: Run unit tests for musicians service
      run: docker exec musicians-container python manage.py test musicians.tests || echo "Musicians service tests failed."

    - name: Run unit tests for users service
      run: docker exec users-container python manage.py test users.tests || echo "Users service tests failed."

    - name: Tear down services
      if: always()
      run: docker-compose down
